name: projeto_final_flutter_2026
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  http: ^1.5.0
  fixnum: ^1.1.1
  protobuf: ^4.2.0
  window_manager: ^0.3.8
  mobx: ^2.3.0
  flutter_mobx: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  protoc_plugin: ^22.5.0
  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/